name: Auto Start VPS

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  start-tmate-session:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
